Students grades:
  output_path: 'D:/scikit/scikit-project-env/output/'   # path to save results
  data_path: 'data/student/student-mat.csv'
  chosen_features: [4,5,9,18,31,33]
  margin: 2

Abalone age:
  data_path: 'data/abalone.data'
  clf_model: 'knn'                                      # model for classification. 'knn' (k-Nearest Neighbors) or 'log_reg' (Logistic Regression)
  k: 5                                                  # k-nearest neighbors
  mode_clf: 1                                           # classifier mode, 0 or 1
  mode_reg: 0                                           # regression mode, 0 or 1 (both available at the same run)

Mnist classification:
  visualize_samples: 0                                  # visualize samples from dataset before training, 0 (no) or 1 (yes)
  n_visualize: 5                                        # how many samples from dataset to visualize
  KNN:                                                  # for k nearest neighbors
    n_neighbors: 5
    n_jobs: -1
  LOGREG:                                               # for logistic regression
    max_iter: 1500
    solver: 'saga'
  MLP:                                                  # for multi layer perceptron
    hls_1: 128                                          # hidden_layer_sizes (hls_1,hls_2)
    hls_2: 64
    early_stopping: True
    n_iter_no_change: 5
  verbose: False                                        # general for all models, True or False

